In [2]:
import numpy as np

In [4]:
spliced = np.load("hgForebrainGlut.spliced.pickle", allow_pickle=True)
unspliced = np.load("hgForebrainGlut.unspliced.pickle", allow_pickle=True)
genes = np.load("gene_name.pickle", allow_pickle=True)

For the velocity analysis lowly expressed (spliced) genes were excluded (requiring 40 minimum expressed counts and detected over 30 cells) and the top 3,000 high variable genes were selected on the basis of a non-parametric fit of the coefficient of variation (CV) using the mean as predictor (using support vector regression). Only 1,706 genes that had unspliced molecule counts above a detection threshold (25 minimum expressed counts and detected over 20 cells) were kept for the analysis. To normalize for the cell size, the counts were divided by the total number of molecules in each cell, and multiplied by the mean number of molecules across all cells. Spliced and unspliced counts were normalized separately. To reduce dimensionality, PCA was performed and the top 19 variable components were kept on the basis of the explained variance ratio profile. Euclidean distance in this reduced PCA space was used to construct a kNN graph (k = 500), using a greedy balanced kNN algorithm that limits each node to a maximum of 4k incoming edges. This graph was used to perform kNN pooling. Velocity-based extrapolation was performed using model I assumptions.

In [3]:
spliced.shape

(32738, 1720)

In [4]:
unspliced.shape

(32738, 1720)

In [5]:
spliced[1,:] > 10

array([False, False, False, ..., False, False, False])

In [6]:
# # sum(spliced[30000,:] > 40)
# counter = 0
# for i in range(32738):
#     if sum(spliced[i,:] >= 5):
#         print(i)
#         counter += 1

23
34
39
41
45
53
92
96
116
118
126
134
138
144
175
207
208
220
226
238
241
248
264
273
303
311
321
323
338
343
360
364
366
377
380
391
395
409
430
444
456
487
508
516
519
524
529
534
538
542
578
580
592
611
623
625
633
635
642
648
672
681
710
731
737
746
769
776
784
788
793
800
890
892
896
898
901
914
921
931
957
966
973
974
976
978
985
992
1003
1008
1011
1013
1014
1018
1019
1028
1034
1073
1094
1098
1106
1124
1126
1143
1144
1162
1208
1217
1220
1228
1236
1240
1271
1274
1293
1295
1320
1323
1327
1349
1358
1393
1403
1423
1435
1443
1457
1468
1481
1490
1495
1497
1500
1532
1538
1629
1631
1664
1667
1677
1684
1685
1703
1733
1734
1749
1777
1811
1815
1816
1817
1820
1823
1825
1836
1842
1843
1858
1862
1864
1869
1879
1885
1896
1908
1909
1923
1926
1929
1934
1964
1965
1971
1973
1975
1979
1980
1990
2012
2022
2032
2037
2041
2042
2048
2049
2057
2083
2087
2096
2105
2150
2154
2157
2187
2194
2245
2254
2263
2269
2273
2274
2277
2283
2294
2301
2310
2337
2345
2351
2380
2389
2428
2456
2459
2512
2527
2532
2537
2

20292
20300
20301
20303
20331
20350
20367
20438
20448
20457
20465
20513
20543
20545
20547
20597
20610
20616
20618
20645
20647
20656
20661
20663
20669
20678
20680
20682
20687
20690
20697
20712
20729
20802
20807
20810
20836
20857
20860
20883
20888
20906
20912
20927
20939
20953
20961
20964
20978
20989
20992
20995
20998
21002
21007
21027
21031
21038
21044
21046
21050
21051
21054
21063
21068
21072
21085
21086
21161
21174
21178
21181
21197
21203
21214
21221
21227
21238
21255
21266
21274
21300
21319
21325
21337
21342
21350
21352
21359
21360
21372
21395
21398
21410
21421
21427
21429
21442
21446
21449
21456
21459
21461
21474
21477
21483
21491
21523
21564
21571
21572
21586
21589
21595
21596
21614
21615
21632
21635
21646
21647
21658
21673
21674
21697
21709
21742
21761
21775
21779
21783
21794
21805
21813
21825
21845
21859
21863
21878
21888
21894
21895
21896
21904
21909
21910
21928
21961
21984
22019
22026
22051
22071
22079
22085
22110
22133
22136
22138
22147
22148
22202
22211
22225
22226
22229
2224

In [7]:
# counter = 0
# for i in range(32738):
#     if sum(spliced[i,:] >= 5) >= 20:
#         print(i)
#         counter += 1

23
53
92
118
208
220
241
338
360
364
380
456
519
534
542
578
625
681
746
788
890
901
966
1011
1013
1018
1019
1028
1073
1098
1143
1217
1220
1240
1327
1435
1495
1497
1532
1538
1667
1811
1823
1836
1842
1858
1869
1896
1908
1965
1980
2012
2032
2041
2049
2057
2083
2096
2154
2157
2194
2245
2254
2273
2277
2337
2380
2428
2459
2512
2527
2532
2594
2622
2626
2646
2683
2686
2732
2752
2769
2777
2787
2815
2926
2933
3002
3012
3060
3077
3152
3208
3235
3343
3371
3481
3493
3594
3652
3674
3676
3678
3682
3736
3868
3879
3909
4022
4099
4116
4155
4166
4187
4343
4364
4397
4630
4637
4661
4720
4794
4798
4830
4891
4892
4895
4913
4944
4967
5120
5194
5234
5249
5305
5310
5332
5362
5437
5440
5483
5544
5548
5589
5602
5654
5721
5867
5869
5881
5903
5933
5947
5949
5951
5987
5992
6072
6221
6260
6377
6441
6452
6554
6563
6572
6630
6640
6649
6691
6692
6764
6775
6791
6818
6819
6820
6836
6841
6926
6927
6930
6972
6977
7076
7078
7081
7091
7133
7136
7138
7166
7190
7271


KeyboardInterrupt: 

In [ ]:
# counter

In [ ]:
# spliced[1,:].shape
sum(spliced[23,:] >= 5) >= 20

In [ ]:
# print(counter)

In [5]:
def gene_expr_filter(data, gene_min_read=20, min_cell_count=30):
    '''
    Filter for genes that are above a certain
    read count cutoff, and above a certain cell coun
    '''
    geneindex = []
    genecount = data.shape[0]
    for i in range(genecount):
        cells_with_min_read_at_gene = sum(data[i,:] >= gene_min_read)
        if cells_with_min_read_at_gene >= min_cell_count:
            geneindex.append(i)
    
    return geneindex


spliced_gene_index = gene_expr_filter(spliced, gene_min_read=5, min_cell_count=20)
    
    

In [6]:
len(spliced_gene_index)

921

In [7]:
unspliced_gene_index = gene_expr_filter(unspliced, gene_min_read=3, min_cell_count=20)

In [8]:
len(unspliced_gene_index )

1930

In [9]:
set(spliced_gene_index) in set(spliced_gene_index)

False

In [10]:
genes_union = set(spliced_gene_index).union(set(unspliced_gene_index))

In [11]:
genes_intersect = set(spliced_gene_index).intersection(set(unspliced_gene_index))

In [15]:
# Normalize gene expression
# len(genes_intersect)

spliced_normcell = spliced / np.sum(spliced, axis=0)
unspliced_normcell = unspliced / np.sum(unspliced, axis=0)

# np.sum(unspliced, axis=0)

In [16]:
spliced_filter = spliced[list(genes_intersect),:]
unspliced_filter = unspliced[list(genes_intersect),:]

In [17]:
spliced_gene_index

[23,
 53,
 92,
 118,
 208,
 220,
 241,
 338,
 360,
 364,
 380,
 456,
 519,
 534,
 542,
 578,
 625,
 681,
 746,
 788,
 890,
 901,
 966,
 1011,
 1013,
 1018,
 1019,
 1028,
 1073,
 1098,
 1143,
 1217,
 1220,
 1240,
 1327,
 1435,
 1495,
 1497,
 1532,
 1538,
 1667,
 1811,
 1823,
 1836,
 1842,
 1858,
 1869,
 1896,
 1908,
 1965,
 1980,
 2012,
 2032,
 2041,
 2049,
 2057,
 2083,
 2096,
 2154,
 2157,
 2194,
 2245,
 2254,
 2273,
 2277,
 2337,
 2380,
 2428,
 2459,
 2512,
 2527,
 2532,
 2594,
 2622,
 2626,
 2646,
 2683,
 2686,
 2732,
 2752,
 2769,
 2777,
 2787,
 2815,
 2926,
 2933,
 3002,
 3012,
 3060,
 3077,
 3152,
 3208,
 3235,
 3343,
 3371,
 3481,
 3493,
 3594,
 3652,
 3674,
 3676,
 3678,
 3682,
 3736,
 3868,
 3879,
 3909,
 4022,
 4099,
 4116,
 4155,
 4166,
 4187,
 4343,
 4364,
 4397,
 4630,
 4637,
 4661,
 4720,
 4794,
 4798,
 4830,
 4891,
 4892,
 4895,
 4913,
 4944,
 4967,
 5120,
 5194,
 5234,
 5249,
 5305,
 5310,
 5332,
 5362,
 5437,
 5440,
 5483,
 5544,
 5548,
 5589,
 5602,
 5654,
 5721,
 586

In [18]:
list(genes_intersect)

[5120,
 2049,
 18946,
 28677,
 13320,
 25100,
 9228,
 26639,
 23572,
 24085,
 534,
 26647,
 7190,
 7707,
 2041,
 12830,
 29216,
 31265,
 2083,
 6692,
 8229,
 17444,
 28713,
 14381,
 25645,
 31792,
 20016,
 22580,
 53,
 28725,
 25140,
 4661,
 8758,
 27708,
 2622,
 20543,
 27200,
 7742,
 31810,
 21572,
 29765,
 6221,
 12365,
 13901,
 24141,
 24142,
 15955,
 15958,
 23131,
 21086,
 19040,
 16993,
 7780,
 23141,
 7271,
 23144,
 2154,
 12394,
 23148,
 9839,
 31857,
 5234,
 8823,
 30329,
 23674,
 25214,
 20610,
 18050,
 28292,
 14471,
 14983,
 3208,
 30347,
 31885,
 2194,
 8851,
 23193,
 13978,
 6818,
 6819,
 30371,
 20647,
 19623,
 681,
 22699,
 9899,
 29357,
 23216,
 19121,
 28341,
 25272,
 5305,
 20155,
 28357,
 17094,
 7878,
 28872,
 208,
 29394,
 5332,
 17620,
 30420,
 29911,
 29918,
 10976,
 2273,
 29410,
 29411,
 7392,
 2277,
 21221,
 16104,
 6377,
 28393,
 241,
 5362,
 24819,
 18676,
 24821,
 17140,
 25331,
 5881,
 26361,
 28923,
 25339,
 26362,
 2815,
 25345,
 24834,
 19203,
 21761,

In [19]:
unspliced.shape

(32738, 1720)

In [20]:
x = np.array([[20,20,20],[30,30,30],[40,40,40]])
x

array([[20, 20, 20],
       [30, 30, 30],
       [40, 40, 40]])

In [21]:
v = np.array([20,30,40])

In [22]:
x.T / v

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [23]:
spliced_normcell_filter = spliced_normcell[list(genes_intersect),:]
unspliced_normcell_filter = unspliced_normcell[list(genes_intersect),:]

In [24]:
# spliced_normcell_filter.append(unspliced_normcell_filter)

normcell_filter_stack = np.stack((spliced_normcell_filter, unspliced_normcell_filter))

In [25]:
normcell_filter_stack[0,:,:]

array([[0.        , 0.        , 0.00021768, ..., 0.00034416, 0.00012241,
        0.00017449],
       [0.00050641, 0.00016672, 0.00021768, ..., 0.00022944, 0.00036724,
        0.00052347],
       [0.00050641, 0.00033344, 0.00021768, ..., 0.00045887, 0.00036724,
        0.00034898],
       ...,
       [0.00050641, 0.00016672, 0.        , ..., 0.00022944, 0.00012241,
        0.        ],
       [0.00185685, 0.00200067, 0.0008707 , ..., 0.00160606, 0.00073448,
        0.00104694],
       [0.00101283, 0.00066689, 0.00043535, ..., 0.00091775, 0.00061207,
        0.00034898]])

In [67]:
normcell_filter_stack.dump("norm_filtered_cells.pickle")

In [68]:
normcell_filter_stack.shape

(2, 231, 1720)

In [54]:
def scale_gene_data(data):
    num_genes = data.shape[0]
    data_new = np.copy(data)
#     print(num_genes)
    for i in range(num_genes):
#         print(i)
        min_val = np.min(data[i,:])
        max_val = np.max(data[i,:])
        norm_vals = (data[i,:] - min_val) / (max_val - min_val)
        data_new[i,:] = norm_vals
    
    return(data_new)

In [55]:
np.min(normcell_filter_stack[0,0,:])

0.0

In [56]:
np.max(normcell_filter_stack[0,0,:])

0.0028804608737397984

In [57]:
data_scaled_layer0 = scale_gene_data(normcell_filter_stack[0,:,:])
data_scaled_layer1 = scale_gene_data(normcell_filter_stack[1,:,:])

In [59]:
np.max(data_scaled_layer1[0,:])

1.0

In [63]:
np.max(normcell_filter_stack[1,3,:])

0.005599764220453876

In [64]:
normcell_filter_stack_scaled = np.stack((data_scaled_layer0, data_scaled_layer1))

In [66]:
normcell_filter_stack_scaled.dump("norm_filtered_cells.scaled.pickle")

NameError: name 'np' is not defined

In [18]:
# genes_intersect
genes_filter = genes[list(genes_intersect)]
genes_filter.dump("gene_name.filtered.pickle")